# Generated by Django 4.2.4 on 2023-08-15 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 7, 24, 55, 183647, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
