# Generated by Django 4.2.4 on 2023-08-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_file_file_tupe_alter_file_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_tupe',
            new_name='file_type',
        ),
    ]
